- src/main/java/org/stellar/sdk/AssetTypeCreditAlphaNum.java
- src/main/java/org/stellar/sdk/AssetTypeCreditAlphaNum12.java
- src/main/java/org/stellar/sdk/AssetTypeCreditAlphaNum4.java
- src/main/java/org/stellar/sdk/AssetTypeNative.java
- src/test/java/org/stellar/sdk/AssetTest.java
This PR also makes `AssetTypeNative`, `AssetTypeCreditAlphaNum4` and `AssetTypeCreditAlphaNum12` classes immutable.
Close #23.
> hashCode method for Asset classes

- src/main/java/org/stellar/sdk/requests/AccountsRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/EffectsRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/LedgersRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/OperationsRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/PathsRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/PaymentsRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/ResponseHandler.java
- src/main/java/org/stellar/sdk/requests/TooManyRequestsException.java
- src/main/java/org/stellar/sdk/requests/TransactionsRequestBuilder.java
- src/main/java/org/stellar/sdk/responses/AccountResponse.java
- src/main/java/org/stellar/sdk/responses/LedgerResponse.java
- src/main/java/org/stellar/sdk/responses/Page.java
- src/main/java/org/stellar/sdk/responses/PathResponse.java
- src/main/java/org/stellar/sdk/responses/Response.java
- src/main/java/org/stellar/sdk/responses/SubmitTransactionResponse.java
- src/main/java/org/stellar/sdk/responses/TransactionResponse.java
- src/main/java/org/stellar/sdk/responses/effects/EffectResponse.java
- src/main/java/org/stellar/sdk/responses/operations/OperationResponse.java
This PR includes Horizon [rate limiting](https://www.stellar.org/developers/horizon/learn/rate-limiting.html) headers in response classes:
* Added `org.stellar.sdk.responses.Response` abstract class that contains rate limitting headers.
* All response classes now extend `Response` class.
* When the client is being throttled `org.stellar.sdk.requests.TooManyRequestsException` will be thrown by `execute()` methods in request classes. This exception contains `Retry-After` header value which is the number of seconds until a new window starts.
Close https://github.com/stellar/java-stellar-sdk/issues/24
> Add rate limiting data to responses

- src/main/java/org/stellar/sdk/AccountFlag.java
- src/main/java/org/stellar/sdk/SetOptionsOperation.java
- src/test/java/org/stellar/sdk/AccountFlagTest.java
This PR introduces `AccountFlag` enum that exposes account flags.
Close https://github.com/stellar/java-stellar-sdk/issues/31
> AccountFlag enum

- src/main/java/org/stellar/sdk/Network.java
- src/main/java/org/stellar/sdk/NoNetworkSelectedException.java
- src/main/java/org/stellar/sdk/Transaction.java
- src/test/java/org/stellar/sdk/NetworkTest.java
- src/test/java/org/stellar/sdk/ServerTest.java
- src/test/java/org/stellar/sdk/TransactionTest.java
- src/test/java/org/stellar/sdk/federation/FederationServerTest.java
- src/test/java/org/stellar/sdk/federation/FederationTest.java
Some users forget to switch to public network (by executing `Network.usePublicNetwork()`) before deploying apps because right now test network is a default choice, selected automatically. This PR changes `Network` module to not select a default network.
> No default network

- src/main/java/org/stellar/sdk/AllowTrustOperation.java
Executing a .toString() on a byte[] will result in a string representation of that byte[]'s memory address. This will cause the assetCode of an AllowTrustOperation that has an asset of asset type ASSET_TYPE_CREDIT_ALPHANUM12 to have an assetCode of some random address. This most certainly was not intended.
> Removing .toString on a byte array in AllowTrustOperation Builder Class

- .gitignore
- src/main/java/org/stellar/sdk/requests/ResponseHandler.java
- src/main/java/org/stellar/sdk/responses/Page.java
- src/main/java/org/stellar/sdk/responses/TypedResponse.java
Fixes the `Page.getNextPage` method by using a new `TypedResponse` interface to allow the `ResponseHandler` to preserve the `TypeToken` on the original response `Page`, so it is present for subsequent page requests.
Also includes an update to the typing of `ResponseHandler`, which was missing the type information on the implemented `org.apache.http.client.ResponseHandler`.  This removes the need for the casts being done wherever `ResponseHandler` is used.
Added some common eclipse ignore settings.
This PR gets `Page.getNextPage` into a functional state but I see two main improvements that could be made here:
1. It doesn't fix the underlying issue that `Page` objects are being requested in different ways from different places.  It's easy for one of the ways to be broken compared to the …
> resolves #66 preserve type information for generic response types

- src/main/java/org/stellar/sdk/Memo.java
- src/main/java/org/stellar/sdk/MemoHashAbstract.java
- src/main/java/org/stellar/sdk/MemoId.java
- src/main/java/org/stellar/sdk/MemoNone.java
- src/main/java/org/stellar/sdk/MemoText.java
- src/main/java/org/stellar/sdk/TimeBounds.java
- src/main/java/org/stellar/sdk/Transaction.java
- src/test/java/org/stellar/sdk/TransactionTest.java
Currently it's not possible to add a new signature to the existing envelope using Java SDK. Added two methods:
* `Transaction.fromEnvelopeXdr(String envelope)`
* `Transaction.fromEnvelopeXdr(TransactionEnvelope envelope)`
that allow creating `Transaction` object from existing envelope to append a new signatures later.
Added helper functions i.e. `fromXdr` and `equals` to some classes to simplify tests.
> Construct Transaction from xdr.TransactionEnvelope

- src/main/java/org/stellar/sdk/Server.java
- src/main/java/org/stellar/sdk/responses/SubmitTransactionTimeoutResponseException.java
- src/main/java/org/stellar/sdk/responses/SubmitTransactionUnknownResponseException.java
- src/test/java/org/stellar/sdk/ServerTest.java
Improves `Server.submitTransaction` by:
- Creating another `OkHttpClient` internal instance used only for
submitting transactions. This special instance has a longer read
timeout.
- Throwing `SubmitTransactionTimeoutResponseException` when Horizon
returns `Timeout` response or HTTP client throws
`SocketTimeoutException`.
- Throwing `SubmitTransactionUnknownResponseException` for unknown
responses with attached response code and body.
This is a breaking change so I want to release it along #112 and #96.
> Improve Server.submitTransaction

- build.gradle
Addresses #122
We cannot use the original jar because of Spring Boot autoconfiguring included things, which then fails because they are old versions. Gson and javax.validation are the two problematic dependencies. 
There are several other things in the dependencies that I'd prefer to not have there like jersey and mockito (why is this a compile dependency).
Shading takes care of removing the conflicts for us; so I simply shaded everything. 
I've signed the contributor agreement.
> shade all dependencies to avoid conflicts

- src/main/java/org/stellar/sdk/Transaction.java
- src/test/java/org/stellar/sdk/OperationTest.java
- src/test/java/org/stellar/sdk/ServerTest.java
- src/test/java/org/stellar/sdk/TransactionTest.java
This PR adds `Transaction.Builder.setTimeout` method to help prevent situations described in https://github.com/stellar/stellar-core/issues/1811. `Transaction.Builder.setTimeout` sets `timebounds.max_time` on a transaction if it is not set yet. It is required to call:
```java
TransactionBuilder.setTimeout(Transaction.Builder.TIMEOUT_INFINITE);
```
if no `timebounds.max_time` should be set to ensure that developers know about possible implications.
> Add Transaction.Builder.setTimeout method

- src/main/java/org/stellar/sdk/Transaction.java
- src/test/java/org/stellar/sdk/TransactionTest.java
changes:
- allow setting a default base fee for all transactions: `Transaction.setDefaultBaseFee(200);`
- allow setting a base fee on a per transaction basis: `txBuilder.setBaseFee(200);`
both functions will throw an IllegalArgumentException if you pass in a base fee that is _less than_ `100`.
tests included.
closes https://github.com/stellar/java-stellar-sdk/issues/176
EDIT @bartekn: close #171
> enable setting custom base fee on transactions as default and on builder

- build.gradle
- src/main/java/org/stellar/sdk/CreatePassiveOfferOperation.java
- src/main/java/org/stellar/sdk/ManageOfferOperation.java
- src/main/java/org/stellar/sdk/Price.java
- src/test/java/org/stellar/sdk/OperationTest.java
This is a small PR to fix #183 that introduces rounding into the process of converting an xdr Price object into a string representation.
> Fix #183: Exception thrown from ManageOfferOperation.fromXDR for certain offers

- src/main/java/org/stellar/sdk/Server.java
- makes Server closable to workaround the issue that okhttpclient does not shut down cleanly.
- adds a second constructor to Server so users can provide their own okhttpclient configuration if they want to
I ran into this today with 0.6.0; seems to be a new issue relative to a 0.4.0. Closing okhttpclient by calling evictAll() on the connection pool fixes things. They may provide a proper solution at some point; in that case we should update the close method on Server.
Note. I assume we want to stick with java 1.6/Android compatibility. If not, we could modify this to AutoCloseable. This works a bit nicer in combination with try with resources introduced in 1.7.
Also see, https://github.com/square/okhttp/issues/3372
> solution to okhttpclient not shutting down cleanly

- src/main/java/org/stellar/sdk/Operation.java
- src/main/java/org/stellar/sdk/xdr/Operation.java
- src/test/java/org/stellar/sdk/OperationTest.java
- src/test/java/org/stellar/sdk/xdr/InflationDecodeTest.java
Attempting to decode an inflation operation using `Transaction.fromEnvelopeXdr` would result in an "Unknown operation body INFLATION" exception. 
This change adds a case for this to support decoding Inflation operations from XDR.
> Add Support for InflationOperation in Operation.fromXdr

- build.gradle
- src/test/java/org/stellar/sdk/TransactionTest.java
When investigating https://github.com/stellar/java-stellar-sdk/issues/184 I realized that there was no unit test which tested that a timeout is required to build a Transaction object.
Also, I decided to use JUnit5 so that we can easily test that certain expressions throw exceptions in a clean manner.
depends on https://github.com/stellar/java-stellar-sdk/pull/211
>  Add test which checks that a Transaction must have a timeout

- .circleci/config.yml
- after_deploy.sh
Previously, the workflow did not run on tags. Now that the correct filter is applied
to the test job, the workflow will run for both releases and merges
> Fix circle ci config

- CHANGELOG.md
- src/main/java/org/stellar/sdk/requests/OperationsRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/PaymentsRequestBuilder.java
- src/main/java/org/stellar/sdk/responses/OperationDeserializer.java
- src/main/java/org/stellar/sdk/responses/operations/OperationResponse.java
- src/test/java/org/stellar/sdk/requests/OperationsRequestBuilderTest.java
- src/test/java/org/stellar/sdk/requests/PaymentsRequestBuilderTest.java
- src/test/java/org/stellar/sdk/responses/OperationsPageDeserializerTest.java
Horizon v0.19 introduces a join parameter when querying for operations. This allows users to get transaction details with operation responses.
fixes https://github.com/stellar/java-stellar-sdk/issues/236
> Allow operations to include transaction data

- CHANGELOG.md
- src/main/java/org/stellar/sdk/Sep10Challenge.java
- src/test/java/org/stellar/sdk/Sep10ChallengeTest.java
fixes https://github.com/stellar/java-stellar-sdk/issues/235
> Add helper method to generate SEP10 challenge

- CHANGELOG.md
- src/main/java/org/stellar/sdk/responses/TransactionResponse.java
- src/test/java/org/stellar/sdk/responses/TransactionDeserializerTest.java
Fixes https://github.com/stellar/java-stellar-sdk/issues/248
>The `fee_paid` field in the Horizon transaction response will be removed when [Horizon 0.25](https://github.com/stellar/go/issues/1812) is released.  The `fee_paid` field has been replaced by `max_fee`, which defines the maximum fee the source account is willing to pay, and fee_charged, which defines the fee that was actually paid for a transaction. See CAP-0005 for more information.
> Remove fee_paid from Transaction response

- CHANGELOG.md
- src/main/java/org/stellar/sdk/requests/OperationsRequestBuilder.java
- src/test/java/org/stellar/sdk/requests/OperationsRequestBuilderTest.java
There was a typo which resulted in an HTTP request with path /operation/<id> instead of /operations/<id>
fixes https://github.com/stellar/java-stellar-sdk/issues/253
> Fix /operations/<id> request

- CHANGELOG.md
- build.gradle
- src/main/java/org/stellar/sdk/ManageDataOperation.java
- src/main/java/org/stellar/sdk/Memo.java
- src/main/java/org/stellar/sdk/MemoText.java
- src/main/java/org/stellar/sdk/SetOptionsOperation.java
- src/main/java/org/stellar/sdk/responses/TransactionDeserializer.java
- src/main/java/org/stellar/sdk/xdr/Error.java
- src/main/java/org/stellar/sdk/xdr/Hello.java
- src/main/java/org/stellar/sdk/xdr/Memo.java
- src/main/java/org/stellar/sdk/xdr/String32.java
- src/main/java/org/stellar/sdk/xdr/String64.java
- src/main/java/org/stellar/sdk/xdr/XdrDataInputStream.java
- src/main/java/org/stellar/sdk/xdr/XdrDataOutputStream.java
- src/main/java/org/stellar/sdk/xdr/XdrString.java
- src/test/java/org/stellar/sdk/XdrDataStreamTest.java
- src/test/java/org/stellar/sdk/xdr/TransactionDecodeTest.java
- xdr/Stellar-transaction.x
Fixes https://github.com/stellar/java-stellar-sdk/issues/257
The Java SDK assumes that all memo texts must be valid UTF 8 strings. However, that assumption is not valid. It turns out that any sequence of bytes is allowed to appear in the memo field (see https://github.com/stellar/go/issues/2022 ).
Therefore, the correct representation for the memo field is a byte array.
> Use bytes to represent memo text

- src/main/java/org/stellar/sdk/InvalidSep10ChallengeException.java
- src/main/java/org/stellar/sdk/Sep10Challenge.java
- src/main/java/org/stellar/sdk/StrKey.java
- src/test/java/org/stellar/sdk/Sep10ChallengeTest.java
- src/test/java/org/stellar/sdk/StrKeyTest.java
This resolves #263 and resolves #235.
Feel free to add comments if you have any questions.
Thanks.
> feat: add support for SEP-0010.

- src/main/java/org/stellar/sdk/requests/AccountsRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/OffersRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/RequestBuilder.java
- src/test/java/org/stellar/sdk/requests/AccountsRequestBuilderTest.java
- src/test/java/org/stellar/sdk/requests/OffersRequestBuilderTest.java
#261 
* feat: add support for `/offers` end-point with query parameters.
* feat: add support for `/accounts` end-point with ?signer and ?asset filters.
> Horizon v1.0.0 Compatibility

- src/main/java/org/stellar/sdk/AbstractTransaction.java
- src/main/java/org/stellar/sdk/FeeBumpTransaction.java
- src/main/java/org/stellar/sdk/Sep10Challenge.java
- src/main/java/org/stellar/sdk/Server.java
- src/main/java/org/stellar/sdk/Transaction.java
- src/test/java/org/stellar/sdk/FeeBumpTransactionTest.java
- src/test/java/org/stellar/sdk/OperationTest.java
- src/test/java/org/stellar/sdk/Sep10ChallengeTest.java
- src/test/java/org/stellar/sdk/ServerTest.java
- src/test/java/org/stellar/sdk/TransactionTest.java
- src/test/java/org/stellar/sdk/xdr/InflationDecodeTest.java
* Implement FeeBumpTransaction builder
* Update SEP 10 implementation to reject fee bump transactions and muxed accounts
* Update SEP 29 implementation to support fee bump transactions
This PR should address all remaining protocol 13 issues in the Java SDK
close https://github.com/stellar/java-stellar-sdk/issues/277
> Implement FeeBumpTransaction builder, update SEP10 and SEP29

- CHANGELOG.md
- src/main/java/org/stellar/sdk/responses/operations/CreatePassiveSellOfferOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/ManageBuyOfferOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/ManageSellOfferOperationResponse.java
- src/test/java/org/stellar/sdk/responses/OperationDeserializerTest.java
> Correct the type of `offerId`

- CHANGELOG.md
- build.gradle
- src/main/java/org/stellar/sdk/responses/operations/RevokeSponsorshipOperationResponse.java
- src/test/java/org/stellar/sdk/responses/OperationsPageDeserializerTest.java
Fixes https://github.com/stellar/java-stellar-sdk/issues/304
The Revoke Sponsorship Operation revokes the sponsorship for a given ledger entry. A ledger entry can be an account, an account signer, an account data entry, a claimable balance, an offer, or a trustline. In the `RevokeSponsorshipOperationResponse` class, the ledger entry is represented as an Optional type for each ledger entry type. The ledger entry type which is actually revoked will have an Optional type with a value and the remaining accessors will have an absent Optional value.
The `Optional.of()` constructor was used in all the ledger entry accessor functions. But, I should have used `Optional.fromNullable()` because `Optional.of()` expects a non-null value where as `Optional.fromNullable()` can take either null or a …
> Fix bug in Revoke Sponsorship Operation response

- build.gradle
After merging https://github.com/stellar/java-stellar-sdk/pull/310 we need to bump the version of gradle before we can create the 0.21.2 release.
> Bump version in gradle

- CHANGELOG.md
- build.gradle
- src/main/java/org/stellar/sdk/Sep10Challenge.java
- src/test/java/org/stellar/sdk/Sep10ChallengeTest.java
resolve #315 
- Updates the SEP-10 utility function parameters to support [SEP-10 v3.1](https://github.com/stellar/stellar-protocol/commit/6c8c9cf6685c85509835188a136ffb8cd6b9c11c)
- A new required `webAuthDomain` parameter was added to the following functions
- `Sep10Challenge#newChallenge(KeyPair, Network, String, String, String, TimeBounds)`
- `Sep10Challenge#readChallengeTransaction(String, String, Network, String, String)`
- `Sep10Challenge#readChallengeTransaction(String, String, Network, String[], String)`
- `Sep10Challenge#verifyChallengeTransactionSigners(String, String, Network, String, String, Set)`
- `Sep10Challenge#verifyChallengeTransactionSigners(String, String, Network, String[], String, Set)`
- `Sep10Challenge#verifyChallengeTransactionThreshold(String, String, Network, …
> feat: add support for SEP-10 v3.1.0.

- CHANGELOG.md
- build.gradle
- src/main/java/org/stellar/sdk/AllowTrustOperation.java
- src/main/java/org/stellar/sdk/ClaimClaimableBalanceOperation.java
- src/main/java/org/stellar/sdk/ClawbackClaimableBalanceOperation.java
- src/main/java/org/stellar/sdk/ClawbackOperation.java
- src/main/java/org/stellar/sdk/Operation.java
- src/main/java/org/stellar/sdk/RevokeClaimableBalanceSponsorshipOperation.java
- src/main/java/org/stellar/sdk/SetTrustlineFlagsOperation.java
- src/main/java/org/stellar/sdk/Util.java
- src/main/java/org/stellar/sdk/responses/effects/TrustlineAuthorizedEffectResponse.java
- src/main/java/org/stellar/sdk/responses/effects/TrustlineAuthorizedToMaintainLiabilitiesEffectResponse.java
- src/main/java/org/stellar/sdk/responses/effects/TrustlineDeauthorizedEffectResponse.java
- src/main/java/org/stellar/sdk/responses/operations/AllowTrustOperationResponse.java
- src/test/java/org/stellar/sdk/OperationTest.java
This PR adds support for building transactions using the operations introduced in CAP 35. Once this PR is merged then we can close https://github.com/stellar/java-stellar-sdk/issues/322
> Add support for CAP 35 operations when building transactions

- src/main/java/org/stellar/sdk/Account.java
Constructors for objects used to wrap primitives should never be used. Doing so is less clear and uses more memory than simply using the desired value.
> account: remove useless Long constructor.

- src/main/java/org/stellar/sdk/AssetTypeCreditAlphaNum.java
Constructors for String objects should never be used. Doing so is less clear and uses more memory than simply using the desired value in the case of strings.
> Remove useless String constructors.

- src/main/java/org/stellar/sdk/SetOptionsOperation.java
Unboxing is the process of putting a primitive value into an analogous object, such as creating an Integer to hold an int value. Unboxing is the process of retrieving the primitive value from such an object.
Since the original value is unchanged during boxing and unboxing, there's no point in doing either when not needed.
> Removed pointless unboxing.

- src/main/java/org/stellar/sdk/ClawbackOperation.java
Overriding or shadowing a variable declared in an outer scope can strongly impact the readability, and therefore the maintainability, of a piece of code. Further, it could lead maintainers to introduce bugs because they think they're using one variable but are really using another.
> clawbackoperation: Renamed fields to avoid shadowing.

- src/main/java/org/stellar/sdk/Claimant.java
- src/main/java/org/stellar/sdk/PaymentOperation.java
- src/main/java/org/stellar/sdk/Server.java
- src/main/java/org/stellar/sdk/requests/StrictReceivePathsRequestBuilder.java
- src/main/java/org/stellar/sdk/responses/effects/TrustlineSponsorshipCreatedEffectResponse.java
- src/main/java/org/stellar/sdk/responses/operations/PathPaymentStrictReceiveOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/PathPaymentStrictSendOperationResponse.java
- src/main/java/org/stellar/sdk/xdr/XdrDataInputStream.java
- src/main/java/org/stellar/sdk/xdr/XdrDataOutputStream.java
Leaving them in reduces the code's readability, since their presence can be confusing.
> removed unused imports.

- src/main/java/org/stellar/sdk/AssetTypeNative.java
A reference to null should never be dereferenced/accessed. The `Object`
in this equals() method could be `null` which would cause a
NullPointerException
> assettypenative: assert that passed object is not null.

- src/main/java/org/stellar/sdk/Sep10Challenge.java
Utility classes, which are collections of static members, are not meant to be instantiated. Even abstract utility classes, which can be extended, should not have public constructors.
Java adds an implicit public constructor to every class which does not define at least one explicitly. Hence, at least one non-public constructor should be defined.
> sep10challenge: added private constructor to hide the public one.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/requests/OperationsRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/TransactionsRequestBuilder.java
- src/main/java/org/stellar/sdk/responses/AssetResponse.java
- src/test/java/org/stellar/sdk/ServerTest.java
- src/test/java/org/stellar/sdk/requests/OperationsRequestBuilderTest.java
- src/test/java/org/stellar/sdk/requests/TransactionsRequestBuilderTest.java
- src/test/java/org/stellar/sdk/responses/AssetsPageDeserializerTest.java
SDK updates for horizon 2.1.0, and pending 2.2.0 changes.
Matches: stellar/new-docs#373
> Updates for /assets and /claimable_balances/*/(operations|transactions) endpoints

- src/main/java/org/stellar/sdk/Asset.java
- src/main/java/org/stellar/sdk/AssetTypePoolShare.java
- src/main/java/org/stellar/sdk/responses/AssetDeserializer.java
- src/main/java/org/stellar/sdk/responses/operations/ChangeTrustOperationResponse.java
- src/test/java/org/stellar/sdk/responses/OperationDeserializerTest.java
Hello, here is draft of changes I think can resolve the npe issue when deser of changetrustresponse, I got hung up on seeing how liquidity pool shares were not defined in XDR Asset, api intentionally throws in XDR Asset ser/deser routines, so I followed that pattern and just addressed enabling the Json deser path in operationresponse for pool share type asset.
> #374: fix npe on liquidity pool trustline in changetrustresponse

- CHANGELOG.md
- src/main/java/org/stellar/sdk/responses/AccountResponse.java
- src/test/java/org/stellar/sdk/responses/AccountDeserializerTest.java
Problem: After account retrieval from server for an account which had liquidity pool balances, the result instance of AccountResponse has a Balance instance for liquidity pool shares, however it was not populating the Balance:liquidityPoolId attribute, attempt to get the PoolId via Balance.getLiquidityPoolId() incorrectly returned an absence(empty Java Optional instance).
Fix: changed serialization to correctly map the server json response attribute for the optional LiquidityPoolId if present, into the Balance:liquidityPoolId object instance.
Closes #375
> #375: Fix missing Liquidity Pool ID in AccountResponse Balance

- CHANGELOG.md
- src/main/java/org/stellar/sdk/requests/TradesRequestBuilder.java
- src/main/java/org/stellar/sdk/responses/TradeResponse.java
- src/main/java/org/stellar/sdk/responses/operations/RevokeSponsorshipOperationResponse.java
- src/test/java/org/stellar/sdk/requests/TradesRequestBuilderTest.java
- src/test/java/org/stellar/sdk/responses/OperationsPageDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/TradesPageDeserializerTest.java
Problem: some offer id values were modeled as string and others as integral longs in request and paired response objects. 
Fix: make the offer id consistently modeled as integral long type in request and response objects.
Note: to achieve the consistency, this introduces breaking changes on existing public classes - changed some existing method signatures for offer ids on request and response models to use long data type instead of string, details in CHANGELOG. Looking for feedback on the approach, if it's worth it or not.
Closes #307
> #307: change offer ids to be represented in requests and response as long data type

- CHANGELOG.md
- src/main/java/org/stellar/sdk/responses/MuxedAccount.java
- src/main/java/org/stellar/sdk/responses/TransactionResponse.java
- src/main/java/org/stellar/sdk/responses/effects/EffectResponse.java
- src/main/java/org/stellar/sdk/responses/effects/TradeEffectResponse.java
- src/main/java/org/stellar/sdk/responses/operations/AccountMergeOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/AllowTrustOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/ChangeTrustOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/ClaimClaimableBalanceOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/ClawbackOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/CreateAccountOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/EndSponsoringFutureReservesOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/OperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/PathPaymentBaseOperationResponse.java
- src/test/java/org/stellar/sdk/responses/EffectsPageDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/OperationDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/TransactionDeserializerTest.java
Problem: the muxed id values from horizon API is a uint64, java was mapping these into `long` which is signed int64 data types which left possibility of overflow. 
Proposed Solution: to safely handle these muxed id values, use the BigInteger data type.
Closes: #384
> Use BigInteger for Muxed ID data type

- CHANGELOG.md
- src/main/java/org/stellar/sdk/AbstractTransaction.java
- src/main/java/org/stellar/sdk/FeeBumpTransaction.java
- src/main/java/org/stellar/sdk/Operation.java
- src/main/java/org/stellar/sdk/Sep10Challenge.java
- src/main/java/org/stellar/sdk/Transaction.java
- src/test/java/org/stellar/sdk/OperationTest.java
Previously, in https://github.com/stellar/java-stellar-sdk/pull/348 we added opt in support for muxed.
But, by default, we rendered muxed accounts in their non muxed encoding.
We are now changing the default behavior so that muxed accounts are rendered using ther 'M' address encoding.
Fixes https://github.com/stellar/java-stellar-sdk/issues/397
> Support muxed accounts by default.

- src/main/java/org/stellar/sdk/responses/AccountResponse.java
- src/test/java/org/stellar/sdk/responses/AccountDeserializerTest.java
resolves #405 
Checks `liquidityPoolID` to see if it is `null`, and calls a constructor that doesn't include the `liquidityPoolID` parameter if so.
> fix AccountResponse().getAsset() NullPointerException

- CHANGELOG.md
- src/main/java/org/stellar/sdk/AbstractTransaction.java
- src/main/java/org/stellar/sdk/KeyPair.java
- src/test/java/org/stellar/sdk/KeyPairTest.java
- src/test/java/org/stellar/sdk/Sep10ChallengeTest.java
- src/test/java/org/stellar/sdk/TransactionTest.java
As part of CAP-40, needed to include payload signer signature generation from `KeyPair` and separate way to add pre-built signatures onto a `Transaction`.
> payload signer signatures

- src/main/java/org/stellar/sdk/responses/PageDeserializer.java
- src/test/java/org/stellar/sdk/responses/AccountsPageDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/TradesPageDeserializerTest.java
LiquidityPoolIDDeserializer is missing from the PageDeserializer.
This fixes #404 and #421.
> LiquidityPoolIDDeserializer is missing from the PageDeserializer.

- src/main/java/org/stellar/sdk/AssetTypeCreditAlphaNum12.java
- src/main/java/org/stellar/sdk/AssetTypeCreditAlphaNum4.java
- src/test/java/org/stellar/sdk/AssetTest.java
> Fix asset compare to when asset code are equals

- src/main/java/org/stellar/sdk/responses/TransactionResponse.java
- src/test/java/org/stellar/sdk/responses/TransactionDeserializerTest.java
Update the Transaction API Response model to include new P19 Preconditions, this also supports the [latest changes in Horizon API ](https://github.com/stellar/go/pull/4361)to Preconditions json model of datetime attribs being expressed in unix epoch.
> Include new Protocol 19 Preconditions on Transaction API resource

- build.gradle
In Windows, the Gradle build throws compile error `unmappable character for encoding Cp1252` at MemoTest.testMemoTextTooLongUtf8() and a couple of other places where `UTF-8` encoding is expected. 
This PR is to force encoding to `UTF-8`.
> Fixed Gradle encoding error

- CHANGELOG.md
- build.gradle
- src/main/java/org/stellar/sdk/Sep10Challenge.java
- src/test/java/org/stellar/sdk/Sep10ChallengeTest.java
Make `Sep10Challenge.verifyTransactionSignatures` resilient against account IDs that are not compliant with ed25519. If a non-compliant account was provided in the list of signers, this account is simply ignored.
Accounts whose ID is not a valid ed25519 public key won't have a signing key, so they can't have signed the challenge transaction.
After the `Sep10Challenge.verifyTransactionSignatures` method finds the intersection between `account IDs that signed the transaction` ∩ `signers provided in the list`, it will return to the caller and the number of accounts and their weight will be verified accordingly.
Close #439.
> bugfix: make `Sep10Challenge.verifyTransactionSignatures` resilient against account IDs that are not compliant with ed25519

- src/main/java/org/stellar/sdk/KeyPair.java
- src/test/java/org/stellar/sdk/KeyPairTest.java
close https://github.com/stellar/java-stellar-sdk/issues/445
`fromSecretSeed(char[] seed)` decodes the seed into a byte array which is eventually passed into EdDSAPrivateKeySpec (defined in a library). EdDSAPrivateKeySpec stores a reference to the byte array in the class definition. So when we clear out the byte array using `Arrays.fill(decoded, (byte) 0);` it will actually affect EdDSAPrivateKeySpec. Consequently, `getSecretSeed()` will end up returning the private key corresponding to all zeros instead of the seed.
> Fix KeyPair.fromSecretSeet on char array

- CHANGELOG.md
- build.gradle
Close https://github.com/stellar/java-stellar-sdk/issues/446
In the 0.35.0 release we upgraded the com.squareup.okhttp3:okhttp dependency from v3 to v4. Bumping that dependency pulled in a dependency on kotlin. This causes "Duplicate Class" errors when using the java stellar sdk on kotlin projects. The fix for this issue is to properly shade all the kotlin dependencies.
> Shade kotlin dependencies

- .circleci/config.yml
- CHANGELOG.md
- build.gradle
Fix the deployment CI that uploads the jar to the GitHub release by updating the image version of cibuilds/github from `0.10` to `0.13`.
Close #449.
In an attempt to fix the deploy job, that's failing at:
https://github.com/stellar/java-stellar-sdk/blob/b2a93410a39f7b39f4dbb8e462214ae119a3996b/.circleci/config.yml#L20-L29
With the error message:
```text
Failed to upload one of assets: one of the goroutines failed: failed to upload asset: /root/project/build/libs/stellar-sdk.jar: failed to upload release asset: /root/project/build/libs/stellar-sdk.jar: stat /root/project/build/libs/stellar-sdk.jar: use of closed file
```
Example of a failed deploy: [deploy (669)](https://app.circleci.com/pipelines/github/stellar/java-stellar-sdk/539/workflows/de14000a-07fe-481c-8707-787d3f58bd48/jobs/669/st …
> Fix the deployment CI that uploads the jar to the GitHub release

- .circleci/config.yml
- CHANGELOG.md
- build.gradle
Fix the deployment CI that uploads the jar to the GitHub release by updating the software being used from https://github.com/tcnksm/ghr to https://github.com/github-release/github-release.
Close #449.
In an attempt to fix the deploy job, that's failing at:
https://github.com/stellar/java-stellar-sdk/blob/417a84bd760321dba1ded0db0b9a32455737424f/.circleci/config.yml#L20-L29
With the error message:
```text
Failed to upload one of assets: one of the goroutines failed: failed to upload asset: /root/project/build/libs/stellar-sdk.jar: failed to upload release asset: /root/project/build/libs/stellar-sdk.jar: Post https://uploads.github.com/repos/stellar/java-stellar-sdk/releases/73913299/assets?name=stellar-sdk.jar: http2: Transport: cannot retry err [stream error: stream ID 5; REFUSED_STREAM] …
```
> Fix the deployment CI that uploads the jar to the GitHub release [2]

- build.gradle
I was able to replicate this problem in Android studio using emulator set at SDK version 28( android 'pie'):
The underlying issue was due to the shadowed jar, which rewrote an unintended 'com.android.org.conscrypt' hardcoded reference in the okhttp3 platform initialization which uses that as default to initialize networking from android:
https://github.com/square/okhttp/blob/parent-4.10.0/okhttp/src/main/kotlin/okhttp3/internal/platform/android/StandardAndroidSocketAdapter.kt#L61
it had a cycle when in error, trying to reference the platform instance while it was inside the platform init routine.
to avoid the problem, I tweaked the shadow config to ignore `com.android.org.conscrypt` ,which stops it from trying to rewrite any refs to that in the .class files in the shadowed jar. 
after …
> fix okhttp3 class loader issue on android platform

- .github/workflows/test-deploy.yml
- CHANGELOG.md
- build.gradle
- src/main/java/org/stellar/sdk/Transaction.java
- src/test/java/org/stellar/sdk/TransactionTest.java
Fix #517 
We need to release a new version, and I have already included it in 96eebcd0b2b95785300ee051a04e01fabe135e46.
Due to the instability of Android testing on API 33 / GitHub Action, I have removed it from the deploy needs. I need some time to investigate this issue as it runs fine on my local machine.
> Fix the bug in Transaction.isSorobanTransaction to accommodate BumpFootprintExpirationOperation.

- .github/workflows/test-deploy.yml
- build.gradle
> define `cursor`, `order` and `limit` in AssetsRequestBuilder object.

- CHANGELOG.md
- build.gradle
- jitpack.yml
- src/main/java/org/stellar/sdk/requests/LiquidityPoolsRequestBuilder.java
- src/main/java/org/stellar/sdk/responses/EffectDeserializer.java
- src/main/java/org/stellar/sdk/responses/effects/LiquidityPoolClaimableAssetAmount.java
- src/main/java/org/stellar/sdk/responses/effects/LiquidityPoolRevokedEffectResponse.java
- src/test/java/org/stellar/sdk/requests/LiquidityPoolsRequestBuilderTest.java
- src/test/java/org/stellar/sdk/responses/EffectDeserializerTest.java
fix #393 
Due to user demand for this fix, let's release it on the master branch.
~~Let's merge #522 first.~~
> fix the issue of unable to parse liquidity_pool_revoked effect properly.

- build.gradle
- src/main/java/org/stellar/sdk/Predicate.java
- src/main/java/org/stellar/sdk/responses/PredicateDeserializer.java
- src/test/java/org/stellar/sdk/PredicateTest.java
- src/test/java/org/stellar/sdk/StrKeyTest.java
- src/test/java/org/stellar/sdk/TransactionBuilderTest.java
Part of #496
- commons-io:commons-io
- org.threeten:threetenbp
- javax.xml.bind:jaxb-api (test dep)
- com.google.code.gson:gson (2.9.0 -> 2.10.1)
- com.squareup.okhttp3:okhttp (4.10.0 -> 4.11.0)
- com.squareup.okhttp3:okhttp-sse (4.10.0 -> 4.11.0)
- com.google.guava:guava (26.0-android -> 32.1.2-android)
- org.mockito:mockito-core (4.6.1 -> 5.5.0) (test dep)
- com.squareup.okhttp3:mockwebserver (4.10.0 -> 4.11.0) (test dep)
- junit:junit (4.12.1 -> 4.13.2) (test dep)
- org.junit.vintage:junit-vintage-engine (4.12.1 -> 5.10.0) (test dep)
> Bump dependencies & Remove unnecessary dependencies.

- CHANGELOG.md
- build.gradle.kts
* Fix the issue of javadocJar not including documentation.
* Publish sourcesJar to the GitHub Release page.
> Fix the issue of javadocJar not including documentation & Publish sourcesJar to the GitHub Release page.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/StrKey.java
- src/test/java/org/stellar/sdk/StrKeyTest.java
We have replaced the base32 library, and their internal implementations are slightly different, which has caused a bug.
fix #540
> Fix the issue where the validity of the encoded strkey is not verified in certain scenarios.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/AccountConverter.java
- src/main/java/org/stellar/sdk/Address.java
- src/main/java/org/stellar/sdk/AllowTrustOperation.java
- src/main/java/org/stellar/sdk/Asset.java
- src/main/java/org/stellar/sdk/BeginSponsoringFutureReservesOperation.java
- src/main/java/org/stellar/sdk/ChangeTrustAsset.java
- src/main/java/org/stellar/sdk/CreateAccountOperation.java
- src/main/java/org/stellar/sdk/CreateClaimableBalanceOperation.java
- src/main/java/org/stellar/sdk/KeyPair.java
- src/main/java/org/stellar/sdk/RevokeAccountSponsorshipOperation.java
- src/main/java/org/stellar/sdk/RevokeDataSponsorshipOperation.java
- src/main/java/org/stellar/sdk/RevokeOfferSponsorshipOperation.java
- src/main/java/org/stellar/sdk/RevokeSignerSponsorshipOperation.java
- src/main/java/org/stellar/sdk/RevokeTrustlineSponsorshipOperation.java
- src/main/java/org/stellar/sdk/SetOptionsOperation.java
- src/main/java/org/stellar/sdk/SetTrustlineFlagsOperation.java
- src/main/java/org/stellar/sdk/StrKey.java
- src/main/java/org/stellar/sdk/Transaction.java
- src/main/java/org/stellar/sdk/TrustLineAsset.java
- src/test/java/org/stellar/sdk/AddressTest.java
- src/test/java/org/stellar/sdk/SetOptionsOperationTest.java
- src/test/java/org/stellar/sdk/SignedPayloadSignerTest.java
- src/test/java/org/stellar/sdk/SignerTest.java
- src/test/java/org/stellar/sdk/StrKeyTest.java
- src/test/java/org/stellar/sdk/TransactionBuilderTest.java
- src/test/java/org/stellar/sdk/TransactionPreconditionsTest.java
Closes #318 
In Soroban, we have many scenarios that require converting strkey into raw data. Making strkey public helps users handle it conveniently.
We will prudently make the following methods public:
- encodeEd25519PublicKey
- decodeEd25519PublicKey
- encodeEd25519SecretSeed
- decodeEd25519SecretSeed
- encodePreAuthTx
- decodePreAuthTx
- encodeSha256Hash
- decodeSha256Hash
- encodeSignedPayload
- decodeSignedPayload
- encodeContract
- decodeContract
In addition, we have modified the names of some functions to be consistent with other SDKs. Since StrKey was not previously public, there will be no destructive updates.
> make `StrKey` public.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/CreatePassiveSellOfferOperation.java
- src/main/java/org/stellar/sdk/ManageBuyOfferOperation.java
- src/main/java/org/stellar/sdk/ManageSellOfferOperation.java
- src/test/java/org/stellar/sdk/OperationTest.java
> Use `Price` instead of `String` to represent prices.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/requests/AccountsRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/EffectsRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/LedgersRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/LiquidityPoolsRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/OffersRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/OperationsRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/OrderBookRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/PaymentsRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/SSEStream.java
- src/main/java/org/stellar/sdk/requests/TradesRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/TransactionsRequestBuilder.java
- src/test/java/org/stellar/sdk/StreamingSmokeTest.java
fix #463, fix #432, fix #210.
Restart SSE to improve reliability if no new messages are received within the timeout period.
> Improve the reliability of `SSEStream`.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/responses/sorobanrpc/GetLedgerEntriesResponse.java
- src/main/java/org/stellar/sdk/responses/sorobanrpc/GetTransactionResponse.java
- src/main/java/org/stellar/sdk/responses/sorobanrpc/SendTransactionResponse.java
- src/main/java/org/stellar/sdk/responses/sorobanrpc/SimulateTransactionResponse.java
- src/test/java/org/stellar/sdk/responses/sorobanrpc/SendTransactionDeserializerTest.java
> Support for the new, optional `diagnosticEventsXdr` field on the `SorobanServer.sendTransaction` method.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/TransactionBuilder.java
- src/test/java/org/stellar/sdk/TransactionBuilderTest.java
Closes #456
See https://github.com/stellar/java-stellar-sdk/issues/456#issuecomment-1257291282
> Other option is to rebuild the tx with TransactionBuilder, and then re-invoke the sign() methods to build out the signatures again.
> Add `TransactionBuilder#TransactionBuilder(Transaction)` constructor.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/Sep10Challenge.java
- src/main/java/org/stellar/sdk/Transaction.java
- src/main/java/org/stellar/sdk/TransactionBuilder.java
- src/main/java/org/stellar/sdk/requests/OffersRequestBuilder.java
- src/main/java/org/stellar/sdk/responses/AccountResponse.java
- src/main/java/org/stellar/sdk/responses/RootResponse.java
- src/main/java/org/stellar/sdk/responses/operations/AllowTrustOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/SetOptionsOperationResponse.java
- src/test/java/org/stellar/sdk/FeeBumpTransactionTest.java
- src/test/java/org/stellar/sdk/TransactionBuilderTest.java
- src/test/java/org/stellar/sdk/requests/OffersRequestBuilderTest.java
- src/test/java/org/stellar/sdk/responses/AccountDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/OperationDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/RootDeserializerTest.java
The following classes and methods have been marked as deprecated in previous releases, and now they have been removed
* `AccountResponse.Signer#getAccountId()` has been removed, use `AccountResponse.Signer#getKey()` instead.
* `OffersRequestBuilder#forAccount(String)` has been removed, use `OffersRequestBuilder#forSeller(String)` instead.
* `RootResponse#getProtocolVersion()` has been removed, use `RootResponse#getCurrentProtocolVersion()` instead.
* `SetOptionsOperationResponse#getSigner()` has been removed, use `SetOptionsOperationResponse#getSignerKey()` instead.
* `Transaction.Builder` has been removed, use `TransactionBuilder` instead.
* `TransactionBuilder#buildTimeBounds(long, long)` has been removed, use `TimeBounds#TimeBounds(long, long)` instead.
* …
> Remove deprecated classes and methods.

- CHANGELOG.md
- examples/src/main/java/network/lightsail/Payment.java
- src/main/java/org/stellar/sdk/Predicate.java
- src/main/java/org/stellar/sdk/responses/PredicateDeserializer.java
- src/test/java/org/stellar/sdk/responses/ClaimableBalancePageDeserializerTest.java
The "inner" inside has been removed, and in its place are "left" and "right," used to represent two conditions.
> refactor!: refactor the way of constructing `Predicate.Or` and `Predicate.And`.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/requests/ResponseHandler.java
- src/main/java/org/stellar/sdk/responses/Response.java
Horizon will no longer return these headers.
> refactor!: remove `rateLimitLimit`, `rateLimitRemaining`, and `rateLimitReset` from the `Response`.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/SorobanServer.java
- src/main/java/org/stellar/sdk/TransactionBuilder.java
- src/test/java/org/stellar/sdk/SorobanServerTest.java
- src/test/java/org/stellar/sdk/TransactionBuilderTest.java
- refactor: `TransactionBuilder#TransactionBuilder(Transaction)` has been removed, because the TransactionBuilder constructed from the transaction may be inconsistent with what the user expects.
- fix: When calling `TransactionBuilder.build()`, the Soroban resource fee will be included in the `fee` of the built transaction.
- fix: fix the issue where invoking `SorobanServer.prepareTransaction` for transactions that have already set `SorobanData` could result in unexpected high fees.
> refactor: optimize fee calculation

- CHANGELOG.md
- src/main/java/org/stellar/sdk/exception/RequestTimeoutException.java
- src/main/java/org/stellar/sdk/requests/ResponseHandler.java
- src/main/java/org/stellar/sdk/responses/Problem.java
- src/test/java/org/stellar/sdk/ServerTest.java
> feat: optimize `RequestTimeoutException`, when a timeout occurs, if the server returns some information, you can read them.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/Auth.java
- src/test/java/org/stellar/sdk/AuthTest.java
See:
https://github.com/stellar/js-stellar-base/issues/780
https://github.com/stellar/js-stellar-base/pull/772
> fix: fix bug with signing auth entries in multi-sig scenarios

- CHANGELOG.md
- src/main/java/org/stellar/sdk/responses/sorobanrpc/GetEventsResponse.java
- src/test/java/org/stellar/sdk/SorobanServerTest.java
- src/test/java/org/stellar/sdk/responses/sorobanrpc/GetEventsDeserializerTest.java
- src/test/resources/responses/sorobanrpc/get_events.json
- src/test/resources/soroban_server/get_events.json
> refactor: add `pagingToken` back to `GetEventsResponse.EventInfo`.

- examples/src/main/java/network/lightsail/GetLedgerEntries.java
- examples/src/main/java/network/lightsail/SorobanCreateContract.java
- examples/src/main/java/network/lightsail/SorobanInvokeContractFunction.java
Add GetLedgerEntries and refactor calling SorobanServer with Closeable interface
> Add GetLedgerEntries and refactor calling SorobanServer with Closeable interface
