- LICENSE
- readme.md
This could use more detail on the installation section.
> add LICENSE and more detail to README

- src/main/java/org/stellar/sdk/ManageDataOperation.java
- src/main/java/org/stellar/sdk/Operation.java
- src/main/java/org/stellar/sdk/responses/OperationDeserializer.java
- src/main/java/org/stellar/sdk/responses/operations/ManageDataOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/OperationResponse.java
- src/test/java/org/stellar/sdk/OperationTest.java
- src/test/java/org/stellar/sdk/responses/OperationDeserializerTest.java
Close https://github.com/stellar/java-stellar-sdk/issues/27
> ManageData operation

- src/main/java/org/stellar/sdk/xdr/XdrDataInputStream.java
- src/main/java/org/stellar/sdk/xdr/XdrDataOutputStream.java
- src/test/java/org/stellar/sdk/OperationTest.java
- src/test/java/org/stellar/sdk/xdr/PaddingTest.java
Close https://github.com/stellar/java-stellar-sdk/issues/45
> Regenerate XDR classes, add XDR padding tests

- src/main/java/org/stellar/sdk/xdr/XdrDataInputStream.java
- src/test/java/org/stellar/sdk/xdr/TransactionDecodeTest.java
More info: https://github.com/stellar/xdrgen/pull/29
Fix #48
> Fix pad() method in XdrInputStream

- src/main/java/org/stellar/sdk/xdr/XdrDataInputStream.java
- src/main/java/org/stellar/sdk/xdr/XdrDataOutputStream.java
- src/test/java/org/stellar/sdk/xdr/XdrDataStreamTest.java
> added utf8 string support for both XdrDataInputStream and XdrDataOutputStream

- src/main/java/org/stellar/sdk/responses/PageDeserializer.java
- src/main/java/org/stellar/sdk/responses/TransactionDeserializer.java
- src/test/java/org/stellar/sdk/responses/TransactionPageDeserializerTest.java
> Fix memo decoding in TransactionDeserializer and add it to PageDeserializer

- src/main/java/org/stellar/sdk/Price.java
> Make Price constructor public, update Price.fromString comment

- src/main/java/org/stellar/sdk/Asset.java
- src/main/java/org/stellar/sdk/Server.java
- src/main/java/org/stellar/sdk/requests/AssetsRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/TradeAggregationsRequestBuilder.java
- src/main/java/org/stellar/sdk/responses/AssetResponse.java
- src/main/java/org/stellar/sdk/responses/GsonSingleton.java
- src/main/java/org/stellar/sdk/responses/LedgerResponse.java
- src/main/java/org/stellar/sdk/responses/TradeAggregationResponse.java
- src/main/java/org/stellar/sdk/responses/TradeResponse.java
- src/main/java/org/stellar/sdk/responses/operations/OperationResponse.java
- src/test/java/org/stellar/sdk/requests/AssetsRequestBuilderTest.java
- src/test/java/org/stellar/sdk/requests/TradeAggregationsRequestBuilderTest.java
- src/test/java/org/stellar/sdk/requests/TradesRequestBuilderTest.java
- src/test/java/org/stellar/sdk/responses/AssetsPageDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/OperationsPageDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/TradeAggregationsPageDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/TradesPageDeserializerTest.java
Endpoints:
* `/assets` - close #59 
* `/trade_aggregations` - close #58 
* `/trades` - close #57 
Fields:
* `transaction_hash` on Operation,
* `created_at` on Operation,
* `base_fee_in_stroops` and `base_reserve_in_stroops` on Ledger.
> Add new Horizon endpoints and fields

- src/main/java/org/stellar/sdk/responses/Page.java
- src/main/java/org/stellar/sdk/responses/Response.java
- src/test/java/org/stellar/sdk/ServerTest.java
Adds tests to code from https://github.com/stellar/java-stellar-sdk/pull/70. Also updates the javadoc for `Page.getNextPage()` to fix the issue here https://github.com/stellar/java-stellar-sdk/issues/66#issuecomment-381365306.
> Test for Page.getNextPage()

- src/main/java/org/stellar/sdk/responses/operations/PathPaymentOperationResponse.java
- src/test/java/org/stellar/sdk/responses/OperationDeserializerTest.java
It looks like path_payment structure has changed but the class is not updated.
Close https://github.com/stellar/java-stellar-sdk/issues/91.
> Update PathPaymentOperationResponse fields

- readme.md
> Update Maven installation instructions

- src/main/java/org/stellar/sdk/requests/TradesRequestBuilder.java
modify return type from TradeResponse to Page<TradeResponse>
> Fix bug in TradesRequestBuilder.excute()

- src/main/java/org/stellar/sdk/responses/EffectDeserializer.java
- src/main/java/org/stellar/sdk/responses/effects/AccountInflationDestinationUpdatedEffectResponse.java
- src/main/java/org/stellar/sdk/responses/effects/DataCreatedEffectResponse.java
- src/main/java/org/stellar/sdk/responses/effects/DataRemovedEffectResponse.java
- src/main/java/org/stellar/sdk/responses/effects/DataUpdatedEffectResponse.java
- src/main/java/org/stellar/sdk/responses/effects/EffectResponse.java
- src/test/java/org/stellar/sdk/responses/EffectDeserializerTest.java
> Add missing effects

- src/main/java/org/stellar/sdk/requests/OrderBookRequestBuilder.java
https://www.stellar.org/developers/horizon/reference/endpoints/orderbook-details.html
> Allow OrderBookRequestBuilder.limit

- src/main/java/org/stellar/sdk/MemoReturnHash.java
- src/test/java/org/stellar/sdk/MemoTest.java
> Fix creating Memo.ReturnHash

- src/main/java/org/stellar/sdk/responses/AccountResponse.java
- src/test/java/org/stellar/sdk/responses/AccountDeserializerTest.java
Implements https://github.com/stellar/go/pull/531 Ensure https://github.com/stellar/go/pull/531 is merged before merging this PR.
> Offer liabilities

- src/main/java/org/stellar/sdk/responses/AccountResponse.java
- src/main/java/org/stellar/sdk/responses/operations/SetOptionsOperationResponse.java
- src/test/java/org/stellar/sdk/responses/AccountDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/OperationDeserializerTest.java
> Support non ed25519 keys in responses

- src/main/java/org/stellar/sdk/responses/operations/PathPaymentOperationResponse.java
- src/test/java/org/stellar/sdk/responses/OperationDeserializerTest.java
> Fix PathPaymentOperationResponse

- gradle/wrapper/gradle-wrapper.properties
> Upgrade Gradle

- src/main/java/org/stellar/sdk/MemoId.java
- src/main/java/org/stellar/sdk/responses/TransactionDeserializer.java
- src/test/java/org/stellar/sdk/MemoTest.java
Fixes https://github.com/stellar/java-stellar-sdk/issues/129
> Treat memo id as an unsigned integer

- src/main/java/org/stellar/sdk/Server.java
- src/main/java/org/stellar/sdk/requests/OperationFeeStatsRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/TradeAggregationsRequestBuilder.java
- src/main/java/org/stellar/sdk/responses/AccountResponse.java
- src/main/java/org/stellar/sdk/responses/OperationFeeStatsResponse.java
- src/main/java/org/stellar/sdk/responses/TradeResponse.java
- src/test/java/org/stellar/sdk/requests/OperationFeeRequestBuilderTest.java
- src/test/java/org/stellar/sdk/requests/TradeAggregationsRequestBuilderTest.java
- src/test/java/org/stellar/sdk/responses/AccountDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/OperationFeeStatsDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/TradesPageDeserializerTest.java
https://github.com/stellar/go/blob/master/services/horizon/CHANGELOG.md#v0150---2018-11-06
> Horizon 0.15.0 Changes

- src/main/java/org/stellar/sdk/Transaction.java
- src/test/java/org/stellar/sdk/TransactionTest.java
> Allow no signatures in Transaction.toEnvelopeXdr

- build.gradle
Confirmed `jitpack.io` deployment works.
Close #168.
> Fix shadow

- src/main/java/org/stellar/sdk/responses/LedgerResponse.java
- src/main/java/org/stellar/sdk/responses/OfferResponse.java
- src/main/java/org/stellar/sdk/responses/RootResponse.java
- src/main/java/org/stellar/sdk/responses/operations/PathPaymentOperationResponse.java
- src/test/java/org/stellar/sdk/responses/LedgerDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/OfferPageDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/OperationDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/RootDeserializerTest.java
> Horizon 0.16.0 features

- readme.md
Allows users to find out the latest published release on jitpack.
> add jitpack badge

- src/main/java/org/stellar/sdk/Server.java
- src/main/java/org/stellar/sdk/Util.java
- src/main/java/org/stellar/sdk/requests/ClientIdentificationInterceptor.java
- src/main/java/org/stellar/sdk/requests/SSEStream.java
- src/test/java/org/stellar/sdk/requests/InterceptorTest.java
resolve #185 
Hi, I have just started learning Java in these two days. If there is anything wrong with this code, please let me know.
Thank you.
> Send Horizon client fingerprint

- src/main/java/org/stellar/sdk/Server.java
- src/main/java/org/stellar/sdk/requests/FeeStatsRequestBuilder.java
- src/main/java/org/stellar/sdk/requests/OperationFeeStatsRequestBuilder.java
- src/main/java/org/stellar/sdk/responses/FeeStatsResponse.java
- src/test/java/org/stellar/sdk/requests/FeeRequestBuilderTest.java
- src/test/java/org/stellar/sdk/responses/FeeStatsDeserializerTest.java
> feat: Update fee stats request to use new `/fee_stats` endpoint

- src/main/java/org/stellar/sdk/responses/AccountResponse.java
- src/main/java/org/stellar/sdk/responses/OperationDeserializer.java
- src/main/java/org/stellar/sdk/responses/operations/CreatePassiveOfferOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/CreatePassiveSellOfferOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/ManageBuyOfferOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/ManageOfferOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/ManageSellOfferOperationResponse.java
- src/test/java/org/stellar/sdk/responses/OperationDeserializerTest.java
I noticed that Horizon responses objects have not been updated. Would be great to release it with other V11 changes in 0.7.0.
> Horizon protocol 11 responses

- src/main/java/org/stellar/sdk/requests/SSEStream.java
- src/main/java/org/stellar/sdk/responses/AccountResponse.java
- src/main/java/org/stellar/sdk/responses/AssetResponse.java
- src/main/java/org/stellar/sdk/responses/LedgerResponse.java
- src/main/java/org/stellar/sdk/responses/OfferResponse.java
- src/main/java/org/stellar/sdk/responses/Pageable.java
- src/main/java/org/stellar/sdk/responses/Response.java
- src/main/java/org/stellar/sdk/responses/TradeResponse.java
- src/main/java/org/stellar/sdk/responses/TransactionResponse.java
- src/main/java/org/stellar/sdk/responses/effects/EffectResponse.java
- src/main/java/org/stellar/sdk/responses/operations/OperationResponse.java
- src/test/java/org/stellar/sdk/responses/AccountDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/AccountsPageDeserializerTest.java
Improves streaming code (and fixes #196) by introducing `Pageable` interface.
> Pageable interface

- src/main/java/org/stellar/sdk/Account.java
- src/main/java/org/stellar/sdk/AccountMergeOperation.java
- src/main/java/org/stellar/sdk/AllowTrustOperation.java
- src/main/java/org/stellar/sdk/AssetTypeCreditAlphaNum.java
- src/main/java/org/stellar/sdk/BumpSequenceOperation.java
- src/main/java/org/stellar/sdk/ChangeTrustOperation.java
- src/main/java/org/stellar/sdk/CreateAccountOperation.java
- src/main/java/org/stellar/sdk/CreatePassiveSellOfferOperation.java
- src/main/java/org/stellar/sdk/InflationOperation.java
- src/main/java/org/stellar/sdk/KeyPair.java
- src/main/java/org/stellar/sdk/ManageBuyOfferOperation.java
- src/main/java/org/stellar/sdk/ManageDataOperation.java
- src/main/java/org/stellar/sdk/ManageSellOfferOperation.java
- src/main/java/org/stellar/sdk/MemoHashAbstract.java
- src/main/java/org/stellar/sdk/MemoId.java
- src/main/java/org/stellar/sdk/MemoNone.java
- src/main/java/org/stellar/sdk/MemoText.java
- src/main/java/org/stellar/sdk/PathPaymentOperation.java
- src/main/java/org/stellar/sdk/PaymentOperation.java
- src/main/java/org/stellar/sdk/Price.java
- src/main/java/org/stellar/sdk/SetOptionsOperation.java
- src/main/java/org/stellar/sdk/TimeBounds.java
- src/main/java/org/stellar/sdk/Transaction.java
- src/main/java/org/stellar/sdk/xdr/DecoratedSignature.java
- src/main/java/org/stellar/sdk/xdr/Signature.java
- src/main/java/org/stellar/sdk/xdr/SignatureHint.java
- src/main/java/org/stellar/sdk/xdr/SignerKey.java
- src/main/java/org/stellar/sdk/xdr/Uint256.java
fixes https://github.com/stellar/java-stellar-sdk/issues/76 and https://github.com/stellar/java-stellar-sdk/issues/98
> Implement hashCode and equals on Stellar classes

- src/main/java/org/stellar/sdk/responses/SubmitTransactionResponse.java
- src/test/java/org/stellar/sdk/ServerTest.java
- src/test/java/org/stellar/sdk/responses/SubmitTransactionResponseTest.java
I took this pr https://github.com/stellar/java-stellar-sdk/pull/146 from @mindicrafter and added an extra commit to use Optional types and to remove a try-catch which was swallowing an exception.
fixes https://github.com/stellar/java-stellar-sdk/issues/144
> Adding SubmitTransactionResponse.getResult()

- src/main/java/org/stellar/sdk/requests/OffersRequestBuilder.java
> fix(OffersRequestBuilder): add Streaming for account offers

- src/main/java/org/stellar/sdk/requests/EventListener.java
- src/main/java/org/stellar/sdk/requests/SSEStream.java
- src/test/java/org/stellar/sdk/StreamingSmokeTest.java
fixes https://github.com/stellar/java-stellar-sdk/issues/175
@jillesvangurp I would appreciate your feedback as well if you have the time
> Add callback to handle SSE failures

- CHANGELOG.md
- build.gradle
- src/main/java/org/stellar/sdk/AccountRequiresMemoException.java
- src/main/java/org/stellar/sdk/Server.java
- src/test/java/org/stellar/sdk/ServerTest.java
> feat: add support for SEP-0029.

- src/main/java/org/stellar/sdk/TimeBounds.java
- src/test/java/org/stellar/sdk/TimeBoundsTest.java
> Optimize the code in `TimeBounds`.

- CHANGELOG.md
- build.gradle
- src/main/java/org/stellar/sdk/FeeBumpTransaction.java
- src/main/java/org/stellar/sdk/Sep10Challenge.java
- src/main/java/org/stellar/sdk/Transaction.java
- src/test/java/org/stellar/sdk/FeeBumpTransactionTest.java
- src/test/java/org/stellar/sdk/Sep10ChallengeTest.java
- src/test/java/org/stellar/sdk/ServerTest.java
- src/test/java/org/stellar/sdk/TransactionTest.java
Fixes https://github.com/stellar/java-stellar-sdk/issues/286
> Generate V1 transactions and allow V0 transactions to be fee bumped

- CHANGELOG.md
- build.gradle
- src/main/java/org/stellar/sdk/BeginSponsoringFutureReservesOperation.java
- src/main/java/org/stellar/sdk/ClaimClaimableBalanceOperation.java
- src/main/java/org/stellar/sdk/CreateClaimableBalanceOperation.java
- src/main/java/org/stellar/sdk/EndSponsoringFutureReservesOperation.java
- src/main/java/org/stellar/sdk/Operation.java
- src/main/java/org/stellar/sdk/Predicate.java
- src/main/java/org/stellar/sdk/RevokeAccountSponsorshipOperation.java
- src/main/java/org/stellar/sdk/RevokeClaimableBalanceSponsorshipOperation.java
- src/main/java/org/stellar/sdk/RevokeDataSponsorshipOperation.java
- src/main/java/org/stellar/sdk/RevokeOfferSponsorshipOperation.java
- src/main/java/org/stellar/sdk/RevokeSignerSponsorshipOperation.java
- src/main/java/org/stellar/sdk/RevokeTrustlineSponsorshipOperation.java
- src/main/java/org/stellar/sdk/responses/PredicateDeserializer.java
- src/test/java/org/stellar/sdk/requests/ClaimableBalancesRequestBuilderTest.java
- src/test/java/org/stellar/sdk/responses/ClaimableBalancePageDeserializerTest.java
Also, bump version and update CHANGELOG
> Add Protocol 14 operation implementations

- CHANGELOG.md
- src/main/java/org/stellar/sdk/Sep10Challenge.java
- src/test/java/org/stellar/sdk/Sep10ChallengeTest.java
> feat: update challenge transaction helpers for SEP-0010 v2.1.0.

- CHANGELOG.md
- build.gradle
- src/main/java/org/stellar/sdk/RevokeAccountSponsorshipOperation.java
- src/main/java/org/stellar/sdk/RevokeClaimableBalanceSponsorshipOperation.java
- src/main/java/org/stellar/sdk/RevokeDataSponsorshipOperation.java
- src/main/java/org/stellar/sdk/RevokeOfferSponsorshipOperation.java
- src/main/java/org/stellar/sdk/RevokeTrustlineSponsorshipOperation.java
- src/test/java/org/stellar/sdk/OperationTest.java
Please see the commit log for details, thank you.
fix #316
> Fix several bugs in revoke operations.

- src/main/java/org/stellar/sdk/FeeBumpTransaction.java
- src/main/java/org/stellar/sdk/Transaction.java
- src/main/java/org/stellar/sdk/requests/RequestBuilder.java
While the performance benefit might be insignificant it's a simple way
to save a few lines of code and improve readability.
> replaced iterators with Collections.AddAll() where applicable.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/Transaction.java
- src/test/java/org/stellar/sdk/ClaimableBalanceIdTest.java
Fixes https://github.com/stellar/java-stellar-sdk/issues/299
> Add getClaimableBalanceId() to determine claimable balance ids

- CHANGELOG.md
- src/main/java/org/stellar/sdk/responses/ImmutableListDeserializer.java
- src/main/java/org/stellar/sdk/responses/MuxedAccount.java
- src/main/java/org/stellar/sdk/responses/OperationDeserializer.java
- src/main/java/org/stellar/sdk/responses/TransactionResponse.java
- src/main/java/org/stellar/sdk/responses/effects/EffectResponse.java
- src/main/java/org/stellar/sdk/responses/effects/TradeEffectResponse.java
- src/main/java/org/stellar/sdk/responses/operations/AccountMergeOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/AllowTrustOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/ChangeTrustOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/ClaimClaimableBalanceOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/ClawbackOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/CreateAccountOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/EndSponsoringFutureReservesOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/OperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/PathPaymentBaseOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/PathPaymentStrictReceiveOperationResponse.java
- src/main/java/org/stellar/sdk/responses/operations/PathPaymentStrictSendOperationResponse.java
- src/test/java/org/stellar/sdk/responses/EffectsPageDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/OperationDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/TransactionDeserializerTest.java
Fixes https://github.com/stellar/java-stellar-sdk/issues/345
> Add support for muxed accounts in Horizon responses

- CHANGELOG.md
- src/main/java/org/stellar/sdk/Sep10Challenge.java
- src/test/java/org/stellar/sdk/Sep10ChallengeTest.java
fixes https://github.com/stellar/java-stellar-sdk/issues/358
> Add 5 minute grace period to SEP-10 challenge parsing function

- build.gradle
So we can release https://github.com/stellar/java-stellar-sdk/pull/366
> Bump version to 0.27.1-beta.0

- CHANGELOG.md
- build.gradle
> Release 0.30.0

- CHANGELOG.md
- build.gradle
updated references for 0.31.0 release
> prepare 0.31.0 release

- src/main/java/org/stellar/sdk/xdr/AllowTrustResultCode.java
- src/main/java/org/stellar/sdk/xdr/ChangeTrustResultCode.java
- src/main/java/org/stellar/sdk/xdr/ClaimPredicate.java
- src/main/java/org/stellar/sdk/xdr/ExtensionPoint.java
- src/main/java/org/stellar/sdk/xdr/InnerTransactionResult.java
- src/main/java/org/stellar/sdk/xdr/LiquidityPoolConstantProductParameters.java
- src/main/java/org/stellar/sdk/xdr/LiquidityPoolDepositOp.java
- src/main/java/org/stellar/sdk/xdr/LiquidityPoolDepositResult.java
- src/main/java/org/stellar/sdk/xdr/LiquidityPoolEntry.java
- src/main/java/org/stellar/sdk/xdr/LiquidityPoolWithdrawOp.java
- src/main/java/org/stellar/sdk/xdr/LiquidityPoolWithdrawResult.java
- src/main/java/org/stellar/sdk/xdr/LiquidityPoolWithdrawResultCode.java
- src/main/java/org/stellar/sdk/xdr/OfferEntryFlags.java
- src/main/java/org/stellar/sdk/xdr/PreconditionType.java
- src/main/java/org/stellar/sdk/xdr/Preconditions.java
- src/main/java/org/stellar/sdk/xdr/PreconditionsV2.java
- src/main/java/org/stellar/sdk/xdr/SignerKey.java
- src/main/java/org/stellar/sdk/xdr/TransactionResultCode.java
- xdr/Stellar-ledger-entries.x
- xdr/Stellar-transaction.x
- xdr/Stellar-types.x
Pulled in the latest changes to the xdr files from core that happened on 4/08:
https://github.com/stellar/stellar-core/pull/3377/commits
XDR Changes did not trigger any functional changes here, recompiled and rerun tests which passed.
> #412: updated xdr files to latest from protocol 19 changes on core

- CHANGELOG.md
- build.gradle
- src/main/java/org/stellar/sdk/responses/AccountResponse.java
- src/test/java/org/stellar/sdk/responses/AccountDeserializerTest.java
Closes #442 
Fix missing  `auth_clawback_enabled` filed  in AccountResponse class.
> Fix missing  in AccountResponse class.

- CHANGELOG.md
- build.gradle
updated notes and maven build version for 0.39.0 release
> release for 0.39.0

- CHANGELOG.md
- build.gradle
Let's merge this PR after merging #530. 
After merging this PR, let's release a new version on the `soroban` branch.
> Bump version to `0.41.0-beta.4`

- .github/workflows/test-deploy.yml
- CHANGELOG.md
- build.gradle.kts
- readme.md
This is the last PR we merged into the soroban branch.
> Bump version to `0.41.0` & update outdated links.

- CHANGELOG.md
- build.gradle.kts
After merging this PR and creating a release, I will merge https://github.com/stellar/java-stellar-sdk-android-spi/pull/1 and also publish a release.
> Bump version to `0.41.1`.

- src/test/java/org/stellar/sdk/requests/AssetsRequestBuilderTest.java
> fix test method name incorrect in AssetsRequestBuilderTest.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/responses/operations/PaymentOperationResponse.java
- src/test/java/org/stellar/sdk/responses/OperationDeserializerTest.java
> Add support for muxed accounts in `PaymentOperationResponse`.

- src/main/java/org/stellar/sdk/responses/SubmitTransactionUnknownResponseException.java
> Add the response code and body to `SubmitTransactionUnknownResponseException`.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/requests/sorobanrpc/GetEventsRequest.java
- src/main/java/org/stellar/sdk/responses/sorobanrpc/GetEventsResponse.java
- src/main/java/org/stellar/sdk/responses/sorobanrpc/GetLatestLedgerResponse.java
- src/test/java/org/stellar/sdk/SorobanServerTest.java
See #559 
| field                                   | before  | now  |
| --------------------------------------- | ------- | ---- |
| GetEventsRequest.startLedger            | String  | Long |
| GetEventsResponse.EventInfo.ledger      | Integer | Long |
| GetLatestLedgerResponse.protocolVersion | Integer | Long |
> Modify the types of some fields in Soroban Request/Response.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/SorobanServer.java
- src/main/java/org/stellar/sdk/requests/sorobanrpc/SimulateTransactionRequest.java
- src/test/java/org/stellar/sdk/SorobanServerTest.java
> Support resource leeway parameter when simulating Soroban transactions.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/responses/sorobanrpc/GetEventsResponse.java
- src/main/java/org/stellar/sdk/responses/sorobanrpc/GetHealthResponse.java
- src/main/java/org/stellar/sdk/responses/sorobanrpc/SimulateTransactionResponse.java
- src/test/java/org/stellar/sdk/SorobanServerTest.java
- src/test/java/org/stellar/sdk/responses/sorobanrpc/GetEventsDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/sorobanrpc/GetHealthDeserializerTest.java
- src/test/java/org/stellar/sdk/responses/sorobanrpc/SimulateTransactionDeserializerTest.java
> feat: add support for Soroban-RPC v21.

- Makefile
- build.gradle.kts
- src/main/java/org/stellar/sdk/xdr/package-info.java
The current XDR document is a bit rough, let's refactor the XDR generator later.
> chore: include `org.stellar.sdk.xdr` in docs.

- CHANGELOG.md
- src/main/java/org/stellar/sdk/Account.java
- src/main/java/org/stellar/sdk/AccountFlag.java
- src/main/java/org/stellar/sdk/AssetAmount.java
- src/main/java/org/stellar/sdk/KeyPair.java
- src/main/java/org/stellar/sdk/LedgerBounds.java
- src/main/java/org/stellar/sdk/MemoNone.java
- src/main/java/org/stellar/sdk/Price.java
- src/main/java/org/stellar/sdk/SignedPayloadSigner.java
- src/main/java/org/stellar/sdk/StrKey.java
- src/main/java/org/stellar/sdk/TimeBounds.java
- src/main/java/org/stellar/sdk/Transaction.java
- src/main/java/org/stellar/sdk/TransactionBuilder.java
- src/main/java/org/stellar/sdk/TransactionPreconditions.java
- src/main/java/org/stellar/sdk/Util.java
- refactor!: `TransactionBuilder.IncrementedSequenceNumberFunc` has been removed.
- refactor!: `Transaction.Builder` has been removed, use `TransactionBuilder` instead.
> refactor!: remove outdated code

- src/main/java/org/stellar/sdk/SorobanServer.java
- src/main/java/org/stellar/sdk/requests/sorobanrpc/GetTransactionsRequest.java
- src/main/java/org/stellar/sdk/responses/sorobanrpc/GetFeeStatsResponse.java
- src/main/java/org/stellar/sdk/responses/sorobanrpc/GetTransactionsResponse.java
- src/test/java/org/stellar/sdk/SorobanServerTest.java
#619 
We do not plan to implement getVersionInfo at the moment to avoid breaking change.
> Supports new Soroban-RPC API

- CHANGELOG.md
- src/main/java/org/stellar/sdk/Server.java
- src/main/java/org/stellar/sdk/exception/BadRequestException.java
- src/main/java/org/stellar/sdk/exception/BadResponseException.java
- src/main/java/org/stellar/sdk/requests/ResponseHandler.java
- src/main/java/org/stellar/sdk/responses/SubmitTransactionAsyncResponse.java
- src/test/java/org/stellar/sdk/ServerTest.java
> feat: add support for Horizon's 'transaction_async' API.

- CHANGELOG.md
- android_test/app/build.gradle.kts
- android_test/app/src/main/java/org/stellar/javastellarsdkdemoapp/MainActivity.kt
- build.gradle.kts
- readme.md
- src/main/java/org/stellar/sdk/requests/SSEStream.java
> fix: fix SSEStream unpredictably throws unwanted IOException("Canceled")

- CHANGELOG.md
- src/main/java/org/stellar/sdk/AbstractTransaction.java
- src/test/java/org/stellar/sdk/FeeBumpTransactionTest.java
> refactor!: change the type of `AbstractTransaction.MIN_BASE_FEE` from `int` to `long`.
